name=input("Enter your name:")
roll_no=int(input("Enter your roll no.:"))
branch=input("Enter your branch:")
print("Your details are:")
print("Name",name)
print("Roll no.:",roll_no)
print("Branch:",branch)
print("5th July")
print("5th July")
print("8th July")
print("9th July")
print("10th July")
